export const themeStyle = {
  appBackgroundColor: "",
  primary: "#FED932",
  textColor: "#000000",
  secondary: "#0089FF",
  activeColor: "#4D6685",
  activeTab: "transparent",
  inaActiveTab: "transparent",
  breadCrumActiveTextColor: "#EB0D0D",
  gradientBackgroundColor: "#16578B",
  sideBarmenuBackgroundColor: "#F6F6F6",
  sidebarTextColor: "black",
  revertActionColor: "#A0A0A0",
  otherActionsColor: "transparent",
  headerColor: {
    backgroundColor: "#E3E3E3",
    subHeaderBgColor: "#f8f8f8",
    dashboardSubheaderBgColor: "#F8F8FB",
    dashboardHeaderBgColor: "#F6F6F6",
    subheaderTextColor: "#000000",
  },
  color: {
    headingTextColor: "#090909",
  },
  cards: {
    cardsBackgroundColor: "",
    cardsTextColor: "",
  },
  table: {
    backgroundColor: "#E1F4FF",
    headingColor: "#090909",
    bodyTextColor: "black",
  },
  dashboardSibeBarFlow: {
    flowSideBarLogoBg: "#000",
    flowDashboardSideBarBg: "#000",
    subMenuSideBarBg: "#D7D7D7",
    activeColorBg: "#000",
    inActiveColorBg: "#181818",
    activeTextColor: "#FFFFFF",
    inActiveTextColor: "#FFF",
  },
  dashboardSideBarView: {
    //viewSideBarBg: "#EDEDED",
    activeColorBg: "#373435",
    activeTextColor: "#c1a528",
    inActiveColorBg: "#EDEDED",
    inActiveTextColor: "#FFF",
  },
};
